# Generated by Django 2.2.1 on 2019-05-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190531_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='approved',
        ),
    ]
