# Generated by Django 2.2.1 on 2019-06-04 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('commit_id', models.CharField(max_length=40, unique=True)),
                ('url', models.URLField(default='https://www.google.com/')),
                ('html_ip', models.FloatField(default=0)),
                ('css_ip', models.FloatField(default=0)),
                ('js_ip', models.FloatField(default=0)),
                ('python_ip', models.FloatField(default=0)),
                ('issue_points', models.FloatField(default=0)),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(blank=True, max_length=25, null=True)),
                ('toc', models.DateTimeField(default=datetime.datetime.now)),
                ('is_added', models.BooleanField(default=False)),
                ('remark', models.CharField(default='-', max_length=1000)),
            ],
        ),
    ]
