# Generated by Django 2.2.2 on 2019-06-12 09:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=40, unique=True)),
                ('url', models.URLField(default='https://www.google.com/')),
                ('html_ip', models.FloatField(default=0)),
                ('css_ip', models.FloatField(default=0)),
                ('js_ip', models.FloatField(default=0)),
                ('py_ip', models.FloatField(default=0)),
                ('issue_points', models.FloatField(default=0)),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(blank=True, max_length=25, null=True)),
                ('toc', models.DateTimeField(default=datetime.datetime.now)),
                ('is_added', models.BooleanField(default=False)),
                ('remark', models.CharField(default='-', max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
