# Generated by Django 2.2.2 on 2019-06-27 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=40, unique=True)),
                ('url', models.URLField(default='https://www.google.com/')),
                ('html_ip', models.FloatField(default=0)),
                ('css_ip', models.FloatField(default=0)),
                ('js_ip', models.FloatField(default=0)),
                ('py_ip', models.FloatField(default=0)),
                ('issue_points', models.FloatField(default=0)),
                ('toc', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=8)),
                ('remark', models.CharField(default='-', max_length=1000)),
                ('time_eval', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
