# Generated by Django 2.2.1 on 2019-06-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190604_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedissue',
            old_name='python_ip',
            new_name='py_ip',
        ),
    ]
