# Generated by Django 2.2.2 on 2019-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190627_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedcommit',
            name='url',
            field=models.URLField(default='https://www.github.com/owner/name'),
        ),
    ]
