# Generated by Django 2.2.1 on 2019-05-27 10:29

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('rollno', models.CharField(max_length=10)),
                ('clg_name', models.CharField(max_length=120)),
                ('branch_year', models.CharField(max_length=120)),
                ('area_interest', models.CharField(max_length=120)),
                ('handle', models.CharField(max_length=120)),
                ('resume', models.FileField(upload_to=registration.models.user_directory_path)),
                ('st_id', models.FileField(upload_to=registration.models.user_directory_path)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
