# Generated by Django 2.2.2 on 2019-07-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
