# Generated by Django 2.2.2 on 2019-07-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
