# Generated by Django 2.2.1 on 2019-06-04 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_auto_20190604_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='student',
            name='function_points',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='report',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_points', models.FloatField(default=0)),
                ('effort', models.FloatField(default=0)),
                ('report', models.URLField(default='https://github.com/aditya3498/SRIP2019-Batch1/wiki')),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(default='SRIP19-BATCH1', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
