# Generated by Django 2.2.1 on 2019-06-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userstudent_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
