# Generated by Django 2.2.1 on 2019-06-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190604_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStudent',
        ),
    ]
