# Generated by Django 2.2.1 on 2019-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_delete_userstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='SRIP19-BATCH1', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='effort',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='function_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='report',
            field=models.URLField(default='https://github.com/aditya3498/SRIP2019-Batch1/wiki'),
        ),
    ]
