# Generated by Django 2.1.4 on 2019-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190604_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch_year',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FirstYear', 'First Year'), ('SecondYear', 'Second Year'), ('ThirdYear', 'Third Year'), ('FourthYear', 'Fourth Year')], default='FirstYear', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('Batch1', 'Batch 1'), ('Batch2', 'Batch 2')], default='Batch1', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
