# Generated by Django 2.2.2 on 2019-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=120)),
                ('url', models.URLField(default='Not available')),
                ('issues', models.PositiveSmallIntegerField(default=0)),
                ('forks', models.PositiveSmallIntegerField(default=0)),
                ('lang', models.CharField(default='Unknown', max_length=120)),
                ('level1', models.BooleanField(default=False)),
                ('level2', models.BooleanField(default=False)),
                ('level3', models.BooleanField(default=False)),
            ],
        ),
    ]
