# Generated by Django 2.2.2 on 2019-06-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190627_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mentors',
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2),
        ),
    ]
