# Generated by Django 2.2.2 on 2019-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        ('project', '0003_auto_20190628_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AddField(
            model_name='project',
            name='mentors',
            field=models.ManyToManyField(blank=True, null=True, to='mentor.Mentor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
    ]
