# Generated by Django 2.2.2 on 2019-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190628_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2),
        ),
    ]
