# Generated by Django 2.2.2 on 2019-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190628_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='level',
        ),
        migrations.AddField(
            model_name='project',
            name='level1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='level2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='level3',
            field=models.BooleanField(default=False),
        ),
    ]
