# Generated by Django 2.2.2 on 2019-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190629_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lang',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='open_issues',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='Not available'),
        ),
    ]
