# Generated by Django 2.2.2 on 2019-06-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190629_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='level2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='level3',
            field=models.BooleanField(default=False),
        ),
    ]
