# Generated by Django 2.2.2 on 2019-06-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190629_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='open_issues',
            new_name='issues',
        ),
    ]
